services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=mock
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
