# Generated by Django 5.2.6 on 2025-09-23 09:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("billing", "Billing"),
                            ("other", "Other"),
                        ],
                        default="shipping",
                        max_length=16,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=160,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=160,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("line2", models.CharField(blank=True, max_length=160)),
                (
                    "city",
                    models.CharField(
                        max_length=120,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_postal_code",
                                message="Enter a valid Japanese postal code (e.g., 100-0001 or 1000001).",
                                regex="^(\\d{3}-\\d{4}|\\d{7})$",
                            )
                        ],
                    ),
                ),
                ("country_code", models.CharField(default="JP", max_length=2)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "full_name"],
                "indexes": [
                    models.Index(fields=["user", "type"], name="ix_address_user_type"),
                    models.Index(fields=["country_code"], name="ix_address_country"),
                    models.Index(fields=["postal_code"], name="ix_address_postal_code"),
                ],
            },
        ),
    ]
